
// Homepage
const HOMEPAGE_PRODUCTS_DATA_FETCH_REQUEST = 'HOMEPAGE:PRODUCTS_DATA:FETCH:REQUEST';
const HOMEPAGE_PRODUCTS_DATA_FETCH_SUCCESS = 'HOMEPAGE:PRODUCTS_DATA:FETCH:SUCCESS';
const HOMEPAGE_PRODUCTS_DATA_FETCH_FAIL = 'HOMEPAGE:PRODUCTS_DATA:FETCH:FAIL';
const HOMEPAGE_PRODUCT_DATA_FETCH_REQUEST = 'HOMEPAGE:PRODUCT_DATA:FETCH:REQUEST';
const HOMEPAGE_PRODUCT_DATA_FETCH_SUCCESS = 'HOMEPAGE:PRODUCT_DATA:FETCH:SUCCESS';
const HOMEPAGE_PRODUCT_DATA_FETCH_FAIL = 'HOMEPAGE:PRODUCT_DATA:FETCH:FAIL';
const HOMEPAGE_CATEGORIES_DATA_FETCH_REQUEST = 'HOMEPAGE:CATEGORIES_DATA:FETCH:REQUEST';
const HOMEPAGE_CATEGORIES_DATA_FETCH_SUCCESS = 'HOMEPAGE:CATEGORIES_DATA:FETCH:SUCCESS';
const HOMEPAGE_CATEGORIES_DATA_FETCH_FAIL = 'HOMEPAGE:CATEGORIES_DATA:FETCH:FAIL';
const HOMEPAGE_PRODUCTS_DATA_SEARCH = 'HOMEPAGE:PRODUCTS_DATA:SEARCH';
const HOMEPAGE_PRODUCTS_DATA_FILTER = 'HOMEPAGE:PRODUCTS_DATA:FILTER';

//Createpage
const CREATEPAGE_PRODUCTS_DATA_SUBMIT_REQUEST = 'CREATEPAGE:PRODUCTS_DATA:SUBMIT:REQUEST';
const CREATEPAGE_PRODUCTS_DATA_SUBMIT_SUCCESS = 'CREATEPAGE:PRODUCTS_DATA:SUBMIT:SUCCESS';
const CREATEPAGE_PRODUCTS_DATA_SUBMIT_FAIL = 'CREATEPAGE:PRODUCTS_DATA:SUBMIT:FAIL';

export {
  HOMEPAGE_PRODUCTS_DATA_FETCH_REQUEST,
  HOMEPAGE_PRODUCTS_DATA_FETCH_SUCCESS,
  HOMEPAGE_PRODUCTS_DATA_FETCH_FAIL,
  HOMEPAGE_CATEGORIES_DATA_FETCH_REQUEST,
  HOMEPAGE_CATEGORIES_DATA_FETCH_SUCCESS,
  HOMEPAGE_CATEGORIES_DATA_FETCH_FAIL,
  HOMEPAGE_PRODUCTS_DATA_SEARCH,
  HOMEPAGE_PRODUCTS_DATA_FILTER,
  HOMEPAGE_PRODUCT_DATA_FETCH_REQUEST,
  HOMEPAGE_PRODUCT_DATA_FETCH_SUCCESS,
  HOMEPAGE_PRODUCT_DATA_FETCH_FAIL,
  CREATEPAGE_PRODUCTS_DATA_SUBMIT_REQUEST,
  CREATEPAGE_PRODUCTS_DATA_SUBMIT_SUCCESS,
  CREATEPAGE_PRODUCTS_DATA_SUBMIT_FAIL
};
