
// Homepage
const HOMEPAGE_PRODUCTS_DATA_FETCH_REQUEST = 'HOMEPAGE:PRODUCTS_DATA:FETCH:REQUEST';
const HOMEPAGE_PRODUCTS_DATA_FETCH_SUCCESS = 'HOMEPAGE:PRODUCTS_DATA:FETCH:SUCCESS';
const HOMEPAGE_PRODUCTS_DATA_FETCH_FAIL = 'HOMEPAGE:PRODUCTS_DATA:FETCH:FAIL';
const HOMEPAGE_CATEGORIES_DATA_FETCH_REQUEST = 'HOMEPAGE:CATEGORIES_DATA:FETCH:REQUEST';
const HOMEPAGE_CATEGORIES_DATA_FETCH_SUCCESS = 'HOMEPAGE:CATEGORIES_DATA:FETCH:SUCCESS';
const HOMEPAGE_CATEGORIES_DATA_FETCH_FAIL = 'HOMEPAGE:CATEGORIES_DATA:FETCH:FAIL';
const HOMEPAGE_PRODUCTS_DATA_SEARCH = 'HOMEPAGE:PRODUCTS_DATA:SEARCH';
const HOMEPAGE_PRODUCTS_DATA_FILTER = 'HOMEPAGE:PRODUCTS_DATA:FILTER';

export {
  HOMEPAGE_PRODUCTS_DATA_FETCH_REQUEST,
  HOMEPAGE_PRODUCTS_DATA_FETCH_SUCCESS,
  HOMEPAGE_PRODUCTS_DATA_FETCH_FAIL,
  HOMEPAGE_CATEGORIES_DATA_FETCH_REQUEST,
  HOMEPAGE_CATEGORIES_DATA_FETCH_SUCCESS,
  HOMEPAGE_CATEGORIES_DATA_FETCH_FAIL,
  HOMEPAGE_PRODUCTS_DATA_SEARCH,
  HOMEPAGE_PRODUCTS_DATA_FILTER
};
